- platform: command_line
  name: Peplink Location
  unique_id: peplink_location
  scan_interval: 300 # 5 minutes
  command: python3 cli-scripts/peplink_location.py

- platform: command_line
  name: Peplink Cellular
  unique_id: peplink_cellular
  scan_interval: 60 # 1 minute
  command: python3 cli-scripts/peplink_cellular.py

- platform: template
  sensors:
    state_of_charge:
      unique_id: state_of_charge
      friendly_name: State of Charge
      unit_of_measurement: "%"
      device_class: battery
      value_template: >
        {% set consumed = states('sensor.battery_consumed') | float %}
        {% set soc_int = states('sensor.state_of_charge_int') | float | round(1) %}
        {% set soc = (((600.0 - consumed) / 600.0) * 100.0) | round(1) %}
        {% if soc == 100 and soc_int < 100 %}{{ soc_int }}{% else %}{{ soc }}{% endif %}

    inverter_state:
      unique_id: inverter_state
      friendly_name: Inverter State
      value_template: >
        {% set state = states('sensor.inverter_state_int') | int %}
        {% if state == 1 %}Charger Only{% elif state == 2 %}Inverter Only{% elif state == 3 %}On{% else %}Off{% endif %}

    battery_power:
      unique_id: battery_power
      friendly_name: Battery Power
      unit_of_measurement: W
      device_class: power
      value_template: >
        {{ ((states.sensor.battery_voltage.state | float) * (states.sensor.battery_current.state | float)) | round(1) }}

    battery_consumed:
      unique_id: battery_consumed
      friendly_name: Battery Consumed
      unit_of_measurement: kWh
      device_class: energy
      value_template: >
        {{ (((states.sensor.battery_consumed_ah.state | float) * (states.sensor.battery_voltage.state | float)) / 1000.0) | round(2) }}

    battery_state:
      unique_id: battery_state
      friendly_name: Battery State
      value_template: >
        {% if states.sensor.battery_state_int.state == '0' %}Idle{% elif states.sensor.battery_state_int.state == '1' %}Charging{% elif states.sensor.battery_state_int.state == '2' %}Discharging{% endif %}
      icon_template: >
        {% if states.sensor.battery_state_int.state == '0' %}mdi:battery{% elif states.sensor.battery_state_int.state == '1' %}mdi:battery-arrow-up{% elif states.sensor.battery_state_int.state == '2' %}mdi:battery-arrow-down{% endif %}
