- platform: template
  switches:
    hot_water_heater:
      unique_id: hot_water_heater
      friendly_name: Hot Water Heater
      icon_template: mdi:water-boiler
      value_template: >
        {{ is_state('light.hot_water_heater_on_off', 'on') }}
      turn_on:
        service: homeassistant.turn_on
        target:
          entity_id: light.hot_water_heater_on_off
      turn_off:
        service: homeassistant.turn_off
        target:
          entity_id: light.hot_water_heater_on_off
