# Default setup
default_config:

# Core
automation: !include_dir_merge_list automations
group: !include integrations/group.yaml
script: !include scripts.yaml

logger:
  logs:
    homeassistant.components.modbus: debug
    pymodbus.client: debug

# Integrations
command_line: !include integrations/command_line.yaml
homekit: !include integrations/homekit.yaml
input_boolean: !include integrations/input_boolean.yaml
input_number: !include integrations/input_number.yaml
input_select: !include integrations/input_select.yaml
modbus: !include integrations/modbus.yaml
mqtt: !include integrations/mqtt.yaml
scene: !include integrations/scene.yaml
sensor: !include integrations/sensor.yaml
