# Configure a default setup of Home Assistant
default_config:

# Core
automation: !include_dir_merge_list automations
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Integrations
modbus: !include integrations/modbus.yaml
sensor: !include integrations/sensor.yaml
