- alias: Kitchen Switch - On
  trigger:
    - platform: device
      domain: mqtt
      device_id: 971f3643ab48f8458c9e2eb2aa34270b
      type: action
      subtype: press_4
  action:
    service: homeassistant.turn_on
    entity_id: scene.bright

- alias: Kitchen Switch - Off
  trigger:
    - platform: device
      domain: mqtt
      device_id: 971f3643ab48f8458c9e2eb2aa34270b
      type: action
      subtype: press_3
  action:
    service: homeassistant.turn_on
    entity_id: scene.goodnight
