- alias: Notify when fully charged
  trigger:
    platform: numeric_state
    entity_id: sensor.state_of_charge_int
    above: 99
    for:
      minutes: 10
  action:
    service: notify.notify
    data:
      title: 🔋 Fully charged!
      message: Batteries at {{ states("sensor.state_of_charge") }}%
      data:
        tag: batteries

- alias: Update inverter input boolean
  trigger:
    - platform: state
      entity_id: sensor.inverter_state_int
    - platform: homeassistant
      event: start
  action:
    service: script.update_inverter

- alias: Control inverter
  trigger:
    platform: state
    entity_id: input_boolean.inverter
  action:
    service: modbus.write_register
    data:
      address: 33
      unit: 227
      hub: Victron
      value: >
        {% if states('input_boolean.inverter') == 'on' %}
          3
        {% else %}
          4
        {% endif %}

- alias: Automatically turn off inverter when there is no load
  trigger:
    platform: numeric_state
    entity_id: sensor.ac_load
    below: 35
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_boolean.inverter_auto_off
    state: "on"
  action:
    service: homeassistant.turn_off
    data:
      entity_id: input_boolean.inverter
