- alias: Notify when fully charged
  trigger:
    platform: numeric_state
    entity_id: sensor.state_of_charge_int
    above: 99
    for:
      minutes: 10
  action:
    service: notify.mobile_app_iphone
    data:
      title: 🔋 Fully charged!
      message: Batteries at {{ states("sensor.state_of_charge") }}%
      data:
        tag: batteries
      target:
        - person.sam

- alias: Update inverter input boolean
  trigger:
    - platform: state
      entity_id: sensor.inverter_state_int
    - platform: homeassistant
      event: start
  action:
    service: script.update_inverter

- alias: Control inverter
  trigger:
    platform: state
    entity_id: input_boolean.inverter
  action:
    service: modbus.write_register
    data:
      address: 33
      unit: 227
      hub: Victron
      value: >
        {% if states('input_boolean.inverter') == 'on' %}
          3
        {% else %}
          4
        {% endif %}
