- alias: Notify when running low on fresh water
  trigger:
    platform: numeric_state
    entity_id: sensor.fresh_water_tank_level
    below: 30
    for:
      minutes: 10
  action:
    service: notify.notify
    data:
      title: 💧 Running Low
      message: Fresh water tank at {{ states("sensor.fresh_water_tank_level") }}%
      data:
        tag: fresh-water

- alias: Notify when gray water tank is getting full
  trigger:
    platform: numeric_state
    entity_id: sensor.gray_water_tank_level
    above: 70
    for:
      minutes: 1
  action:
    service: notify.notify
    data:
      title: 💦 Getting Full
      message: Gray water tank level at {{ states("sensor.gray_water_tank_level") }}%
      data:
        tag: gray-water

- alias: Notify when urine tank is getting full
  trigger:
    platform: numeric_state
    entity_id: sensor.urine_tank_level
    above: 70
    for:
      minutes: 1
  action:
    service: notify.notify
    data:
      title: 🚽 Empty Urine Tank Now
      message: Urine tank level at {{ states("sensor.urine_tank_level") }}%
      data:
        tag: urine-water

- alias: Close gray water valve
  trigger:
    platform: numeric_state
    entity_id: sensor.gray_water_tank_level
    below: 1
    for:
      minutes: 1
  condition:
    alias: Gray water valve is open
    condition: state
    entity_id: switch.gray_water_dump_valve
    state: "on"
  action:
    - service: homeassistant.turn_off
      target:
        entity_id: switch.gray_water_dump_valve
    - service: notify.notify
      data:
        title: 🔧 Closed gray water drain
        message: Gray water tank at {{ states("sensor.gray_water_tank_level") }}%
        data:
          tag: gray-water

- alias: Close fresh water valve
  trigger:
    platform: numeric_state
    entity_id: sensor.fresh_water_tank_level
    below: 1
    for:
      minutes: 1
  condition:
    alias: Fresh water valve is open
    condition: state
    entity_id: switch.fresh_water_dump_valve
    state: "on"
  action:
    - service: homeassistant.turn_off
      target:
        entity_id: switch.fresh_water_dump_valve
    - service: notify.notify
      data:
        title: 🔧 Closed fresh water drain
        message: Fresh water tank at {{ states("sensor.fresh_water_tank_level") }}%
        data:
          tag: fresh-water
