esphome:
  name: cab

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:
  level: INFO

api:
  encryption:
    key: !secret esphome_cab_key

ota:
  password: !secret esphome_cab_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  fast_connect: true

web_server:
  local: true
  ota: false

binary_sensor:
  - platform: gpio
    name: "Cab Button 1 Top"
    pin:
      number: GPIO16 # Blue
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - light.toggle: trail_lights
  - platform: gpio
    name: "Cab Button 1 Bottom"
    pin:
      number: GPIO17 # Red
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - light.toggle: flood_lights
  - platform: gpio
    name: "Cab Button 2 Top"
    pin:
      number: GPIO5 # Yellow
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Cab Button 2 Bottom"
    pin:
      number: GPIO18 # White
      inverted: true
      mode:
        input: true
        pullup: true

light:
  - platform: binary
    name: Trail Lights
    id: trail_lights
    icon: mdi:car-light-high
    output: trail_lights_output
  - platform: binary
    name: Flood Lights
    id: flood_lights
    icon: mdi:track-light
    output: flood_lights_output

output:
  - platform: gpio
    id: trail_lights_output
    pin: GPIO19
  - platform: gpio
    id: flood_lights_output
    pin: GPIO21
