esphome:
  name: garage

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:
  level: INFO

api:
  password: !secret esphome_garage_password

ota:
  password: !secret esphome_garage_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  fast_connect: true

web_server:
  local: true
  ota: false

light:
  - platform: neopixelbus
    variant: SK6812
    type: GRBW
    num_leds: 144
    pin: GPIO13
    name: Garage Lightstrip
