esphome:
  name: lights

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:

api:
  password: !secret esphome_lights_password

ota:
  password: !secret esphome_lights_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

light:
  - platform: monochromatic
    output: lights1
    name: Ceiling Lights 1

  - platform: monochromatic
    output: lights2
    name: Ceiling Lights 2

  - platform: monochromatic
    output: lights3
    name: Ceiling Lights 3

  - platform: monochromatic
    output: lights4
    name: Ceiling Lights 4

output:
  - platform: ledc
    pin: GPIO27
    id: lights1
    frequency: 1220Hz

  - platform: ledc
    pin: GPIO14
    id: lights2
    frequency: 1220Hz

  - platform: ledc
    pin: GPIO12
    id: lights3
    frequency: 1220Hz

  - platform: ledc
    pin: GPIO13
    id: lights4
    frequency: 1220Hz
