esphome:
  name: lights

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:
  level: INFO

api:
  encryption:
    key: !secret esphome_lights_key

ota:
  platform: esphome
  password: !secret esphome_lights_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  fast_connect: true

web_server:
  local: true
  ota: false

light:
  - platform: monochromatic
    output: lights1
    name: Ceiling Lights 1
    icon: mdi:light-recessed
    restore_mode: RESTORE_DEFAULT_ON

  - platform: monochromatic
    output: lights2
    name: Ceiling Lights 2
    icon: mdi:light-recessed
    restore_mode: RESTORE_DEFAULT_ON

  - platform: monochromatic
    output: lights3
    name: Ceiling Lights 3
    icon: mdi:light-recessed
    restore_mode: RESTORE_DEFAULT_ON

  - platform: monochromatic
    output: lights4
    name: Ceiling Lights 4
    icon: mdi:light-recessed
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: ledc
    id: lights1
    pin: GPIO14

  - platform: ledc
    id: lights2
    pin: GPIO27

  - platform: ledc
    id: lights3
    pin: GPIO26

  - platform: ledc
    id: lights4
    pin: GPIO25
