esphome:
  name: lights

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:

api:
  password: !secret esphome_lights_password

ota:
  password: !secret esphome_lights_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

light:
  - platform: monochromatic
    output: gpio_2
    name: Ceiling Lights

output:
  - platform: ledc
    pin: GPIO2
    id: gpio_2
    frequency: 1220Hz
