esphome:
  name: valves

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:

api:
  password: !secret esphome_valves_password

ota:
  password: !secret esphome_valves_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

switch:
  - platform: gpio
    name: Fresh Water Dump Valve
    pin: GPIO5

  - platform: gpio
    name: Gray Water Dump Valve
    pin: GPIO18
